### ISSUE TITLE
Doesn't seem to work with vim8

### ISSUE THREAD

**Issue by kantord** [voldikss/coc-browser#6]
Has this been tested using vim8? I tried with both Firefox and Chrome, and haven't managed to set it up.

To reproduce, follow the [instructions](https://github.com/voldikss/coc-browser#installation), but with vim8 instead of neovim

**Comment by voldikss** [comment]
![image](https://user-images.githubusercontent.com/20282795/92459910-d7ecea00-f1f9-11ea-81b5-a129a3bbbe90.png)

Hi @kantord 
It's strange...I just tested on my PC and it works on vim8.

```
VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Aug 20 2020 22:02:30)
```

**Comment by kantord** [comment]
Is there a way to debug it? Seeing some debug messages or such?

**Comment by voldikss** [comment]
Actually it uses a pretty simple way to do completion. 
1. Browser extension sends words to the local server
2. Local server receives the data and stores them in the files
3. Coc.nvim get completion candidates by reading those files.

The files containing words are normally located in `C:\Users\xxx\AppData\Local\coc\extensions\coc-browser-data`. So you can check if the files exists.

I haven't implemented any debug feature for the extension. I'll try to implement that when I have free time.

**Comment by kantord** [comment]
I am on Arch Linux, where would the files be located in that case?

**Comment by kantord** [comment]
I have this folder `~/.config/coc/extensions/coc-browser-data` but it's empty

**Comment by voldikss** [comment]
Hmm seems the local server hasn't received the words.

Daniel Kantor <notifications@github.com> 于 2020年9月8日周二 下午6:58写道：

**Comment by voldikss** [comment]
Does this extension work on nvim?

Ꮩ0ᏞᎠIᏦSS <dyzplus@gmail.com> 于 2020年9月8日周二 下午7:02写道：

**Comment by kantord** [comment]
Sorry, I didn't have time to try it in nvim yet.

After a quick look at the source code for the browser plugin: is this meant to work with multiple open vim instances at the same time? Is it possible that it only worked in one specific vim instance?

**Comment by kantord** [comment]
I realized that it works in one of my vim instances, but not in any further instance

**Comment by voldikss** [comment]
I forget how I designed it's multiple instance mode before. But I just tested it. and the result is (I used neovim to do the test),

It works with every nvim instance I've opened.

**Comment by kantord** [comment]
It's conflicting with another server running on 8888.
