### ISSUE TITLE
Conflicting with something else running no 8888

### ISSUE THREAD

**Issue by kantord** [voldikss/coc-browser#8]
This plugin seems to conflict with another server running on port 8888.

Could the default port be changed to something even more obscure? For example 8896

Or maybe it's a better solution to make the port customizable? This would probably involve a change in the browser plugin.

**Comment by voldikss** [comment]
Please update the chrome extension and click the icon to configure the port.

**Comment by kantord** [comment]
This is amazing!! Thanks, @voldikss
