### ISSUE TITLE
Doesn't seem to support non-English characters

### ISSUE THREAD

**Issue by kantord** [voldikss/coc-browser#9]
![2021-01-09T11:12+01:00](https://user-images.githubusercontent.com/3704904/104089057-d432a800-526b-11eb-86d5-f457ec1e5603.png)

Looking at the screenshot, it would be expected that "felfüggesztette" would show up in the suggestions, but it doesn't. Words that only contain characters also present in the English alphabet word fine, for example Twitter, tesztre, azokat, etc.

**Comment by kantord** [comment]
It's probably because of this line: https://github.com/voldikss/coc-browser/blob/master/extension/src/content.js#L18

By default, JavaScript regular expressions don't support unicode.

There is a way to enable this though: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/unicode

**Comment by voldikss** [comment]
Also closed due to #10
